# Site settings
title: "@brosyhmi"
author: Syahmi Fauzi
email: brosyahmifauzi@gmail.com
description: >-
  Syahmi is a self-taught front-end web developer
  based in Malaysia..
keywords: "syahmifauzi, syahmi, syhmi, brosyhmi, developer, freelance, responsive, frontend, portfolio, msf, msfaf, msfworks"

url: "https://www.syahmifauzi.com"
permalink: /blog/:year/:month/:day/:title/

repository: syahmifauzi/repo-name
github_username: syahmifauzi
twitter_username: brosyhmi
facebook_username: brosyhmi
instagram_username: brosyhmi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "README.md", "offline.txt", "Gemfile", "Gemfile.lock"]
